version: '2'
 
services:

  nginx:
        build: docker/nginx 
        ports:
            - 8000:8000
        networks:
          app_subnet:
           ipv4_address:  172.31.39.160

        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
  php:
        build: docker/php7-fpm # Get our Dockerfile configuration
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/babycare-server-symfony
            
networks:                                                                                                                                                                                                                                                                      
  app_subnet:                                                                                                                                                                                                                                                                      
    external: true