<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * BabysitterRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class BabysitterRepository extends DocumentRepository
{

     public $dm;

    public function __construct(DocumentManager $dm ) {
    
      $this->dm = $dm;
   }

     public function AddBabysitter($babysitter)
    {

   
    $this->dm->persist($babysitter);
    $this->dm->flush();

    
  }
}
