<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ParentRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ParentRepository extends DocumentRepository
{

     public function AddParent($parent)
    {

    $dm = $this->get('doctrine_mongodb')->getManager();
    $dm->persist($parent);
    $dm->flush();

    
  }
  
}
