<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;
/**
 * ParentRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ParentRepository extends DocumentRepository
{
    
     public $dm;

    public function __construct(DocumentManager $dm ) {
     
      $this->dm = $dm;
   }

     public function AddParent($parent)
    {

   
    $this->dm->persist($parent);
    $this->dm->flush();

    
  }
  
}
